### ISSUE TITLE
In post its Postgres but in Github its Faunadb. 

### ISSUE THREAD

**Issue by muke5hy** [pbteja1998/nextjs-starter#4]
Hi, 
In Your post, you have used Postgres but in this git repo you are using faunadb, how do we use Postgres? 

Just curious what was the reason to move to fauna?

**Comment by pbteja1998** [comment]
One way to use Postgres is through Prisma. You can use NextAuth's Prisma adapter to setup authentication with Prisma. Check out their documentation [here](https://next-auth.js.org/schemas/adapters#prisma-adapter). You just have to set the `DATABASE_URL` env variable to your Postgres DB URL. You can also follow [this blog post](https://dev.to/prisma/passwordless-authentication-with-next-js-prisma-and-next-auth-5g8g) for setting it up with Postgres. 

Another way is to go back to the commit where I shifted to Fauna from Postgres. Go to [this URL](https://github.com/pbteja1998/nextjs-starter/tree/f9999329bf79a8d2aa8ce05dcc9cadb658817fda), instead of cloning the repo in that link, download the zip and you should be good to go. If you end up following this method, you might want to also add the changes in https://github.com/pbteja1998/nextjs-starter/commit/6efe5ced0fd00ff07a165fe10ba88dcc9e574ff8 which have the best practices for loading the web fonts.

Going forward, I will try to publish releases so that it would be easy to go back to whatever version that anyone wants and also publish the changelog.

I will also add another branch that uses Prisma + Postgres instead of Fauna DB.

--- 

Check out the tweets at [here](https://twitter.com/pbteja1998/status/1345422354873159680?s=20) and [here](https://twitter.com/pbteja1998/status/1345422422468481025?s=20) to know the reason why I shifted to Fauna DB. This starter repo is the exact one I use for any new applications that I build with Next.js. And because of that, this repo continues to evolve as I build more and more applications. I want this starter to be an end-to-end solution that you can use to deploy scalable applications to production. We are a long way from that, but we will gradually be getting there.
